<a href="https://colab.research.google.com/github/peperjet/deep-learning/blob/main/SBERT_chatbot_260513.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BERT의 문장 임베딩을 이용한 한국어 챗봇 만들기

In [ ]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting sentence-transformers
  Using cached sentence_transformers-5.5.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.57.6)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.34.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Using cached sentence_transformers-5.5.0-py3-none-any.whl (588 kB)
Installing collected packages: sentence-transformers
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 2.2.2
    Uninstalling sentence-transformers-2.2.2:
      Successfully uninstalled sentence-transformers-2.2.2
Successfully installed sentence-transformers-5.5.0

GPU 확인하기

In [ ]:
import torch

print(torch.cuda.is_available())

True

모델 로드

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('jhgan/ko-sroberta-multitask')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/744 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/585 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/442M [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

문장 임베딩 테스트

In [ ]:
sentences = ['안녕하세요', '오늘 기분이 좋아요']

embeddings = model.encode(sentences)

print(embeddings.shape)

(2, 768)

문장 2개를 각각 숫자 768개짜리 벡터로 바꿨다는 뜻.

train_data의 각 질문(Q)을 하나씩 꺼내서 BERT 모델로 숫자 벡터로 바꾸고

그 결과를 embedding이라는 새 열(column)에 저장하기

파일 다운로드

In [ ]:
!wget https://raw.githubusercontent.com/songys/Chatbot_data/master/ChatbotData.csv

--2026-05-13 14:21:18--  https://raw.githubusercontent.com/songys/Chatbot_data/master/ChatbotData.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 889842 (869K) [text/plain]
Saving to: ‘ChatbotData.csv’

ChatbotData.csv     100%[===================>] 868.99K  --.-KB/s    in 0.006s

2026-05-13 14:21:18 (151 MB/s) - ‘ChatbotData.csv’ saved [889842/889842]

In [ ]:
import pandas as pd

train_data = pd.read_csv("ChatbotData.csv")
train_data.head()

                 Q            A  label
0           12시 땡!   하루가 또 가네요.      0
1      1지망 학교 떨어졌어    위로해 드립니다.      0
2     3박4일 놀러가고 싶다  여행은 언제나 좋죠.      0
3  3박4일 정도 놀러가고 싶다  여행은 언제나 좋죠.      0
4          PPL 심하네   눈살이 찌푸려지죠.      0

In [ ]:
# 데이터 개수 확인
print(len(train_data))
print(train_data.columns)

11823
Index(['Q', 'A', 'label'], dtype='object')

In [ ]:
# 임베딩 생성

train_data['embedding'] = train_data['Q'].apply(lambda x: model.encode(x))

In [ ]:
# 임베딩 확인
train_data.head()

,Q,A,label,embedding
0,12시 땡!,하루가 또 가네요.,0,"[-0.19072695, 0.3214757, 0.59873754, 0.4461786..."
1,1지망 학교 떨어졌어,위로해 드립니다.,0,"[0.12320574, 0.6423682, 0.6853603, -0.42912346..."
2,3박4일 놀러가고 싶다,여행은 언제나 좋죠.,0,"[0.024357503, -0.22393543, 0.22917706, -0.4501..."
3,3박4일 정도 놀러가고 싶다,여행은 언제나 좋죠.,0,"[0.036285225, -0.21048254, 0.07269403, -0.5403..."
4,PPL 심하네,눈살이 찌푸려지죠.,0,"[0.022030605, 0.7055219, -0.17157203, 0.165971..."

In [ ]:
from numpy import dot
from numpy.linalg import norm
import numpy as np

코사인 유사도 함수 : 두 문장이 얼마나 비슷한 방향인지 점수 계산

In [ ]:
def cos_sim(A, B):
    return dot(A, B) / (norm(A) * norm(B))

In [ ]:
def return_answer(question):

    embedding = model.encode(question)

    train_data['score'] = train_data['embedding'].apply(
        lambda x: cos_sim(x, embedding)
    )

    return train_data.loc[train_data['score'].idxmax()]['A']

In [ ]:
return_answer("배고파")

'얼른 맛난 음식 드세요.'

In [ ]:
# 확실하게 보려면
print(return_answer("배고파"))

얼른 맛난 음식 드세요.

실제 챗봇처럼 여러번 질문하기

In [ ]:
while True:

    question = input("나: ")

    if question == "종료":
        break

    answer = return_answer(question)

    print("챗봇:", answer)

나: 지금 몇시니
챗봇: 시간은 지금도 흐르고 있어요.
나: 종료

사용자가 질문 입력하면 질문을 BERT 숫자벡터로 변환한다

기존 질문들과 비교하여 가장 비슷한 질문의 답변 출력한다

- 생성이 아닌 가장 비슷한 질문 찾아서 답변 꺼내오기 방식

In [29]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [30]:
import os
# 내 드라이브에서 ipynb 찾기
for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file.endswith('.ipynb'):
            print(os.path.join(root, file))

/content/drive/MyDrive/Colab Notebooks/today_260127.ipynb
/content/drive/MyDrive/Colab Notebooks/today_260126.ipynb
/content/drive/MyDrive/Colab Notebooks/today_260129.ipynb
/content/drive/MyDrive/Colab Notebooks/today_260131.ipynb
/content/drive/MyDrive/Colab Notebooks/python2_260131.ipynb
/content/drive/MyDrive/Colab Notebooks/wordcloud_260131.ipynb
/content/drive/MyDrive/Colab Notebooks/plotly_260131.ipynb
/content/drive/MyDrive/Colab Notebooks/plotly_260202.ipynb
/content/drive/MyDrive/Colab Notebooks/plotly_260203.ipynb
/content/drive/MyDrive/Colab Notebooks/plotly_260204.ipynb
/content/drive/MyDrive/Colab Notebooks/plotly2_260204.ipynb
/content/drive/MyDrive/Colab Notebooks/plotly_260205.ipynb
/content/drive/MyDrive/Colab Notebooks/book_260223.ipynb
/content/drive/MyDrive/Colab Notebooks/spotify_project.ipynb
/content/drive/MyDrive/Colab Notebooks/LinearAlgebra_RREF.ipynb
/content/drive/MyDrive/Colab Notebooks/graph260314.ipynb
/content/drive/MyDrive/Colab Notebooks/m260316.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled0.ipynb
/content/drive/MyDrive/Colab Notebooks/movielens_cf.ipynb
/content/drive/MyDrive/Colab Notebooks/credit_260325.ipynb
/content/drive/MyDrive/Colab Notebooks/train_260325.ipynb
/content/drive/MyDrive/Colab Notebooks/apt_260328.ipynb
/content/drive/MyDrive/Colab Notebooks/apt2_260328.ipynb
/content/drive/MyDrive/Colab Notebooks/dacon3_260331 (2).ipynb
/content/drive/MyDrive/Colab Notebooks/dacon_260331.ipynb
/content/drive/MyDrive/Colab Notebooks/dacon3_260331 (1).ipynb
/content/drive/MyDrive/Colab Notebooks/dacon3_260331.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled1.ipynb
/content/drive/MyDrive/Colab Notebooks/flight_delay_260401.ipynb
/content/drive/MyDrive/Colab Notebooks/movie_admissions_260402.ipynb
/content/drive/MyDrive/Colab Notebooks/cosine_260406.ipynb
/content/drive/MyDrive/Colab Notebooks/5-2. similarity_measures.ipynb
/content/drive/MyDrive/Colab Notebooks/5-1. cosine_similarity.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled2.ipynb
/content/drive/MyDrive/Colab Notebooks/6-4. linear_regression.ipynb
/content/drive/MyDrive/Colab Notebooks/7_3_Neural_Network.ipynb
/content/drive/MyDrive/Colab Notebooks/7-2. activation_function.ipynb
/content/drive/MyDrive/Colab Notebooks/7-10. text_classification_using_neural_networks.ipynb
/content/drive/MyDrive/Colab Notebooks/7_2_perceptron.ipynb
/content/drive/MyDrive/Colab Notebooks/api_test_260411.ipynb
/content/drive/MyDrive/Colab Notebooks/9_8_pretrained_word_embedding.ipynb
/content/drive/MyDrive/Colab Notebooks/10_4_imdb_movie_review_sentiment_analysis.ipynb
/content/drive/MyDrive/Colab Notebooks/fast_text_260413.ipynb
/content/drive/MyDrive/Colab Notebooks/12-4. named_entity_recognition_using_bilstm (1).ipynb
/content/drive/MyDrive/Colab Notebooks/wine.ipynb
/content/drive/MyDrive/Colab Notebooks/14-3. bleu.ipynb
/content/drive/MyDrive/Colab Notebooks/13_1_byte_pair_encoding.ipynb
/content/drive/MyDrive/Colab Notebooks/12-2. part_of_speech_tagging_with_bidirectional_lstm.ipynb
/content/drive/MyDrive/Colab Notebooks/13_2_sentencepiece.ipynb
/content/drive/MyDrive/Colab Notebooks/13_2_naver_movie_review.ipynb
/content/drive/MyDrive/Colab Notebooks/algorithm_260425.ipynb
/content/drive/MyDrive/Colab Notebooks/factorial_260427.ipynb
/content/drive/MyDrive/Colab Notebooks/hashtable_260428.ipynb
/content/drive/MyDrive/Colab Notebooks/preorder_260429.ipynb
/content/drive/MyDrive/Colab Notebooks/stack_260429.ipynb
/content/drive/MyDrive/Colab Notebooks/attention_260502.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled3.ipynb
/content/drive/MyDrive/Colab Notebooks/transformers_260511.ipynb
/content/drive/MyDrive/Colab Notebooks/KoBERT_260512.ipynb
/content/drive/MyDrive/Colab Notebooks/KoBERT_260513.ipynb
/content/drive/MyDrive/Colab Notebooks/SBERT_chatbot_260513.ipynb

In [31]:
# 코랩에서 실행
!pip install nbformat

import nbformat

with open("/content/drive/MyDrive/Colab Notebooks/SBERT_chatbot_260513.ipynb", "r") as f:
    nb = nbformat.read(f, as_version=4)

# 위젯 메타데이터 제거
if 'widgets' in nb.metadata:
    del nb.metadata['widgets']

with open("/content/drive/MyDrive/Colab Notebooks/SBERT_chatbot_260513.ipynb", "w") as f:
    nbformat.write(nb, f)

print("완료!")

Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.6)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
완료!